#!/bin/bash
################################
# Squelette de conditionnement #
################################
MODULE_ENVIRONNEMENT=3
clear;

#SI:
if [ $MODULE_ENVIRONNEMENT=1 ]
 #Alors:
 then
  echo "MODULE_ENVIRONNEMENT = $MODULE_ENVIRONNEMENT"
  
 #Sinon Si
 elif [ $MODULE_ENVIRONNEMENT=2 ]
  #alors:
  then
   echo "RC = $MODULE_ENVIRONNEMENT"

 #Sinon Si
 elif [ $MODULE_ENVIRONNEMENT=3 ]
  #alors:
  then
   echo "RC = $MODULE_ENVIRONNEMENT"

 #Sinon
 else
  echo "Erreur sur le script"
fi '> 0.sh ; sh 0.sh ;
